#!/bin/bash
# Fail2ban module
# Configures intrusion prevention for SSH and nginx

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/utils.sh"

# Install fail2ban
install_fail2ban() {
    log_step "Installing fail2ban"
    
    install_packages "fail2ban"
    
    log_success "Fail2ban installed"
}

# Configure fail2ban main settings
configure_fail2ban() {
    local bantime="${FAIL2BAN_BANTIME:-3600}"
    local maxretry="${FAIL2BAN_MAXRETRY:-5}"
    local ssh_port="${SSH_PORT:-22}"
    
    log_step "Configuring fail2ban"
    
    # Create local configuration (overrides defaults)
    local jail_local="/etc/fail2ban/jail.local"
    
    cat > "$jail_local" << EOF
# Fail2ban configuration
# Generated by server setup on $(date)

[DEFAULT]
# Ban duration in seconds (default: 1 hour)
bantime = $bantime

# Time window for counting failures (10 minutes)
findtime = 600

# Number of failures before ban
maxretry = $maxretry

# Action to take when banning
banaction = ufw

# Ignore local addresses
ignoreip = 127.0.0.1/8 ::1

# Backend for monitoring log files
backend = systemd

# Email notifications (configure if needed)
# destemail = admin@example.com
# sender = fail2ban@example.com
# mta = sendmail
# action = %(action_mwl)s

[sshd]
enabled = true
port = $ssh_port
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 7200

[sshd-ddos]
enabled = true
port = $ssh_port
filter = sshd-ddos
logpath = /var/log/auth.log
maxretry = 6
bantime = 3600

[nginx-http-auth]
enabled = true
port = http,https
filter = nginx-http-auth
logpath = /var/log/nginx/error.log
maxretry = 3
bantime = 3600

[nginx-limit-req]
enabled = true
port = http,https
filter = nginx-limit-req
logpath = /var/log/nginx/error.log
maxretry = 10
findtime = 60
bantime = 7200

[nginx-botsearch]
enabled = true
port = http,https
filter = nginx-botsearch
logpath = /var/log/nginx/access.log
maxretry = 2
bantime = 86400

[nginx-badbots]
enabled = true
port = http,https
filter = nginx-badbots
logpath = /var/log/nginx/access.log
maxretry = 2
bantime = 86400
EOF

    log_success "Fail2ban jail configuration created"
}

# Create custom nginx filters
create_nginx_filters() {
    log_step "Creating custom nginx filters"
    
    # Filter for bad bots and scanners
    cat > /etc/fail2ban/filter.d/nginx-badbots.conf << 'EOF'
# Fail2ban filter for bad bots and vulnerability scanners

[Definition]
failregex = ^<HOST> .* "(GET|POST|HEAD).*(\.php|\.asp|\.aspx|\.jsp|\.cgi|wp-login|wp-admin|xmlrpc|phpmyadmin|myadmin|admin\.php|\.env|\.git|\.htaccess|\.htpasswd|config\.php|wp-config|shell|eval\(|base64_decode).*" (400|403|404|444)
            ^<HOST> .* ".*(?:sqlmap|nikto|nessus|nmap|masscan|zgrab|gobuster|dirbuster|wpscan).*"

ignoreregex =
EOF

    # Filter for suspicious requests
    cat > /etc/fail2ban/filter.d/nginx-suspicious.conf << 'EOF'
# Fail2ban filter for suspicious requests

[Definition]
failregex = ^<HOST> .* "(GET|POST).*(union.*select|concat.*\(|information_schema|benchmark\(|sleep\(|waitfor|declare.*@|exec.*\(|etc/passwd|/proc/self|\.\./).*"
            ^<HOST> .* ".*(<script|javascript:|onerror=|onload=|onclick=).*"

ignoreregex =
EOF

    # Filter for 404 errors (potential scanning)
    cat > /etc/fail2ban/filter.d/nginx-404.conf << 'EOF'
# Fail2ban filter for excessive 404 errors

[Definition]
failregex = ^<HOST> .* "(GET|POST|HEAD).*" 404

ignoreregex = \.(jpg|jpeg|png|gif|ico|css|js|woff|woff2|ttf|svg)
EOF

    log_success "Custom nginx filters created"
}

# Configure UFW action for fail2ban
configure_ufw_action() {
    log_step "Configuring UFW action for fail2ban"
    
    local ufw_action="/etc/fail2ban/action.d/ufw.conf"
    
    # Check if action already exists
    if [[ -f "$ufw_action" ]]; then
        log_info "UFW action already exists"
        return
    fi
    
    cat > "$ufw_action" << 'EOF'
# Fail2ban action for UFW

[Definition]
actionstart =
actionstop =
actioncheck =

actionban = ufw insert 1 deny from <ip> to any comment "Fail2ban: <name>"
actionunban = ufw delete deny from <ip> to any
EOF

    log_success "UFW action configured"
}

# Set up log rotation for fail2ban
setup_logrotate() {
    log_step "Configuring fail2ban log rotation"
    
    cat > /etc/logrotate.d/fail2ban << 'EOF'
/var/log/fail2ban.log {
    weekly
    rotate 4
    compress
    delaycompress
    missingok
    notifempty
    postrotate
        /usr/bin/fail2ban-client flushlogs 1>/dev/null
    endscript
}
EOF

    log_success "Log rotation configured"
}

# Start and enable fail2ban
start_fail2ban() {
    log_step "Starting fail2ban service"
    
    systemctl enable fail2ban
    systemctl restart fail2ban
    
    # Wait for service to start
    sleep 2
    
    if systemctl is-active --quiet fail2ban; then
        log_success "Fail2ban is running"
    else
        log_error "Fail2ban failed to start"
        journalctl -u fail2ban -n 20
        return 1
    fi
}

# Show fail2ban status
show_status() {
    log_step "Fail2ban status"
    echo ""
    fail2ban-client status
    echo ""
}

# Main function
setup_fail2ban() {
    check_root
    
    log_step "Starting fail2ban configuration"
    print_separator
    
    install_fail2ban
    configure_ufw_action
    create_nginx_filters
    configure_fail2ban
    setup_logrotate
    start_fail2ban
    show_status
    
    print_separator
    log_success "Fail2ban configuration complete"
    
    save_state "FAIL2BAN_CONFIGURED" "$(date +%Y%m%d_%H%M%S)"
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    setup_fail2ban
fi
