#!/bin/bash
# Nginx module
# Configures nginx for secure static site hosting

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/utils.sh"

# Install nginx
install_nginx() {
    log_step "Installing nginx"
    
    install_packages "nginx"
    
    # Stop nginx for configuration
    systemctl stop nginx 2>/dev/null || true
    
    log_success "Nginx installed"
}

# Configure main nginx settings
configure_nginx_main() {
    local workers="${NGINX_WORKERS:-auto}"
    
    log_step "Configuring nginx main settings"
    
    backup_file "/etc/nginx/nginx.conf"
    
    cat > /etc/nginx/nginx.conf << EOF
# Nginx configuration
# Generated by server setup on $(date)

user www-data;
worker_processes $workers;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

# Worker connections
events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

http {
    ##
    # Basic Settings
    ##
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    server_tokens off;  # Hide nginx version

    # Increase bucket size for long domain names
    server_names_hash_bucket_size 64;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ##
    # SSL Settings
    ##
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    # OCSP Stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 1.1.1.1 8.8.8.8 valid=300s;
    resolver_timeout 5s;

    ##
    # Logging Settings
    ##
    log_format main '\$remote_addr - \$remote_user [\$time_local] "\$request" '
                    '\$status \$body_bytes_sent "\$http_referer" '
                    '"\$http_user_agent" "\$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;

    ##
    # Gzip Settings
    ##
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;

    ##
    # Rate Limiting
    ##
    limit_req_zone \$binary_remote_addr zone=general:10m rate=10r/s;
    limit_conn_zone \$binary_remote_addr zone=addr:10m;

    ##
    # Security Headers (applied in server blocks)
    ##

    ##
    # Virtual Host Configs
    ##
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}
EOF

    log_success "Nginx main configuration complete"
}

# Create security snippets
create_security_snippets() {
    log_step "Creating security snippets"
    
    local snippets_dir="/etc/nginx/snippets"
    mkdir -p "$snippets_dir"
    
    # Security headers snippet
    cat > "$snippets_dir/security-headers.conf" << 'EOF'
# Security Headers

# Prevent clickjacking
add_header X-Frame-Options "SAMEORIGIN" always;

# Prevent MIME type sniffing
add_header X-Content-Type-Options "nosniff" always;

# XSS Protection
add_header X-XSS-Protection "1; mode=block" always;

# Referrer Policy
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# Content Security Policy (permissive default for static sites)
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https:; frame-ancestors 'self';" always;

# Permissions Policy
add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
EOF

    # SSL parameters snippet (for sites with SSL)
    cat > "$snippets_dir/ssl-params.conf" << 'EOF'
# SSL Parameters
# Note: ssl_dhparam is added separately by generate_dhparam function

# Enable HSTS
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
EOF

    # Static file caching snippet
    cat > "$snippets_dir/static-cache.conf" << 'EOF'
# Static File Caching

# Cache static assets
location ~* \.(jpg|jpeg|png|gif|webp|ico|css|js|pdf|woff|woff2|ttf|svg|eot)$ {
    expires 30d;
    add_header Cache-Control "public, immutable";
    include snippets/security-headers.conf;
    access_log off;
}

# Cache HTML for shorter period
location ~* \.html$ {
    expires 1h;
    add_header Cache-Control "public";
    include snippets/security-headers.conf;
}
EOF

    # Common security blocks
    cat > "$snippets_dir/security-blocks.conf" << 'EOF'
# Block common attack patterns

# Block access to hidden files
location ~ /\. {
    deny all;
    access_log off;
    log_not_found off;
}

# Block access to backup and source files
location ~* \.(bak|config|sql|fla|psd|ini|log|sh|inc|swp|dist|orig|tmp)$ {
    deny all;
    access_log off;
    log_not_found off;
}

# Block WordPress-specific attacks (even if not using WordPress)
location ~* (wp-config\.php|xmlrpc\.php|wp-login\.php) {
    deny all;
    access_log off;
    log_not_found off;
}

# Block common vulnerability scanners
location ~* (\.php|\.asp|\.aspx|\.jsp|\.cgi)$ {
    deny all;
    access_log off;
    log_not_found off;
}
EOF

    log_success "Security snippets created"
}

# Create site configuration
create_site_config() {
    local domain="${DOMAIN:-example.com}"
    local web_root="${WEB_ROOT:-/var/www}"
    local site_root="$web_root/$domain"
    local deploy_user="${DEPLOY_USER:-deploy}"
    
    log_step "Creating site configuration for $domain"
    
    # Create web root directory
    mkdir -p "$site_root/html"
    mkdir -p "$site_root/logs"
    
    # Set ownership
    chown -R "$deploy_user:www-data" "$site_root"
    chmod -R 755 "$site_root"
    
    # Create a placeholder index.html
    cat > "$site_root/html/index.html" << EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to $domain</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }
        .container {
            text-align: center;
            padding: 2rem;
        }
        h1 { font-size: 3rem; margin-bottom: 1rem; }
        p { font-size: 1.2rem; opacity: 0.9; }
    </style>
</head>
<body>
    <div class="container">
        <h1>$domain</h1>
        <p>Your server is configured and ready!</p>
        <p>Deploy your Eleventy site to get started.</p>
    </div>
</body>
</html>
EOF
    
    chown "$deploy_user:www-data" "$site_root/html/index.html"
    
    # Remove default site
    rm -f /etc/nginx/sites-enabled/default
    
    # Create site configuration (HTTP only initially, certbot will add HTTPS)
    cat > "/etc/nginx/sites-available/$domain" << EOF
# Site configuration for $domain
# Generated by server setup on $(date)

# Rate limiting
limit_req_zone \$binary_remote_addr zone=${domain//\./_}:10m rate=10r/s;

server {
    listen 80;
    listen [::]:80;
    server_name $domain www.$domain;
    
    root $site_root/html;
    index index.html index.htm;
    
    # Logging
    access_log $site_root/logs/access.log main;
    error_log $site_root/logs/error.log warn;
    
    # Security
    include snippets/security-headers.conf;
    include snippets/security-blocks.conf;
    
    # Rate limiting
    limit_req zone=${domain//\./_} burst=20 nodelay;
    
    # Main location
    location / {
        try_files \$uri \$uri/ \$uri.html =404;
    }
    
    # Static file caching
    include snippets/static-cache.conf;
    
    # Custom error pages
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
EOF

    # Enable the site
    ln -sf "/etc/nginx/sites-available/$domain" "/etc/nginx/sites-enabled/$domain"
    
    log_success "Site configuration created for $domain"
    log_info "Web root: $site_root/html"
    
    save_state "SITE_DOMAIN" "$domain"
    save_state "SITE_ROOT" "$site_root"
}

# Generate DH parameters
generate_dhparam() {
    local dhparam_file="/etc/nginx/dhparam.pem"
    local ssl_params="/etc/nginx/snippets/ssl-params.conf"
    
    log_step "Generating DH parameters (this may take a while)"
    
    if [[ -f "$dhparam_file" ]]; then
        log_info "DH parameters already exist"
        return
    fi
    
    openssl dhparam -out "$dhparam_file" 2048
    chmod 600 "$dhparam_file"
    
    # Add DH params to SSL snippet if not already present
    if ! grep -q "ssl_dhparam" "$ssl_params"; then
        echo "ssl_dhparam $dhparam_file;" >> "$ssl_params"
    fi
    
    log_success "DH parameters generated"
}

# Test and start nginx
start_nginx() {
    log_step "Testing and starting nginx"
    
    # Test configuration
    if nginx -t; then
        log_success "Nginx configuration is valid"
    else
        log_error "Nginx configuration is invalid"
        exit 1
    fi
    
    # Enable and start nginx
    systemctl enable nginx
    systemctl start nginx
    
    if systemctl is-active --quiet nginx; then
        log_success "Nginx is running"
    else
        log_error "Nginx failed to start"
        journalctl -u nginx -n 20
        exit 1
    fi
}

# Show nginx status
show_status() {
    log_step "Nginx status"
    echo ""
    systemctl status nginx --no-pager -l
    echo ""
}

# Main function
setup_nginx() {
    check_root
    
    log_step "Starting nginx configuration"
    print_separator
    
    install_nginx
    configure_nginx_main
    create_security_snippets
    create_site_config
    generate_dhparam
    start_nginx
    show_status
    
    print_separator
    log_success "Nginx configuration complete"
    
    save_state "NGINX_CONFIGURED" "$(date +%Y%m%d_%H%M%S)"
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    setup_nginx
fi
