#!/bin/bash
# Unattended upgrades module
# Configures automatic security updates

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/utils.sh"

# Install unattended-upgrades
install_unattended_upgrades() {
    log_step "Installing unattended-upgrades"
    
    install_packages "unattended-upgrades" "apt-listchanges" "needrestart"
    
    log_success "Unattended-upgrades installed"
}

# Configure unattended-upgrades
configure_unattended_upgrades() {
    local email="${ADMIN_EMAIL:-}"
    
    log_step "Configuring unattended-upgrades"
    
    backup_file "/etc/apt/apt.conf.d/50unattended-upgrades"
    
    cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
// Unattended-Upgrades configuration
// Generated by server setup

// Which packages to upgrade automatically
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
    "${distro_id}:${distro_codename}-updates";
};

// Packages to NOT automatically upgrade
Unattended-Upgrade::Package-Blacklist {
    // Uncomment packages you want to hold back
    // "nginx";
    // "linux-image-*";
};

// Split the upgrade into smallest possible chunks
Unattended-Upgrade::MinimalSteps "true";

// Automatically reboot if required (at 3 AM)
Unattended-Upgrade::Automatic-Reboot "true";
Unattended-Upgrade::Automatic-Reboot-Time "03:00";

// Only reboot if no users are logged in
Unattended-Upgrade::Automatic-Reboot-WithUsers "false";

// Remove unused kernel packages
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

// Remove unused dependencies
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Remove new unused dependencies after upgrade
Unattended-Upgrade::Remove-New-Unused-Dependencies "true";

// Automatically fix interrupted dpkg
Unattended-Upgrade::AutoFixInterruptedDpkg "true";

// Enable logging
Unattended-Upgrade::SyslogEnable "true";
Unattended-Upgrade::SyslogFacility "daemon";

// Verbose logging
Unattended-Upgrade::Verbose "false";
Unattended-Upgrade::Debug "false";
EOF

    # Add email notification if email is configured
    if [[ -n "$email" ]]; then
        cat >> /etc/apt/apt.conf.d/50unattended-upgrades << EOF

// Email notifications
Unattended-Upgrade::Mail "$email";
Unattended-Upgrade::MailReport "on-change";
EOF
    fi
    
    log_success "Unattended-upgrades configured"
}

# Configure auto-upgrades
configure_auto_upgrades() {
    log_step "Configuring automatic updates"
    
    cat > /etc/apt/apt.conf.d/20auto-upgrades << 'EOF'
// Auto-upgrades configuration
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
EOF

    log_success "Automatic updates configured"
}

# Configure needrestart for automatic service restarts
configure_needrestart() {
    log_step "Configuring needrestart"
    
    local needrestart_conf="/etc/needrestart/needrestart.conf"
    
    if [[ -f "$needrestart_conf" ]]; then
        backup_file "$needrestart_conf"
        
        # Set to automatically restart services
        sed -i "s/^#\$nrconf{restart} = 'i';/\$nrconf{restart} = 'a';/" "$needrestart_conf"
        
        log_success "Needrestart configured for automatic service restarts"
    fi
}

# Set up upgrade notification
setup_upgrade_notification() {
    log_step "Setting up upgrade notifications"
    
    # Create a script to check for and log upgrades
    cat > /usr/local/bin/check-upgrades << 'EOF'
#!/bin/bash
# Check for available upgrades and log summary

LOG_FILE="/var/log/upgrade-check.log"
DATE=$(date '+%Y-%m-%d %H:%M:%S')

# Update package lists
apt-get update -qq

# Count available upgrades
UPGRADES=$(apt-get -s upgrade 2>/dev/null | grep -c "^Inst" || echo 0)
SECURITY=$(apt-get -s upgrade 2>/dev/null | grep -c "^Inst.*security" || echo 0)

echo "$DATE - Available upgrades: $UPGRADES (Security: $SECURITY)" >> "$LOG_FILE"

# If there are security updates, log them
if [[ $SECURITY -gt 0 ]]; then
    echo "Security updates available:" >> "$LOG_FILE"
    apt-get -s upgrade 2>/dev/null | grep "^Inst.*security" >> "$LOG_FILE"
fi
EOF
    chmod +x /usr/local/bin/check-upgrades
    
    # Create systemd timer for daily checks
    cat > /etc/systemd/system/check-upgrades.service << 'EOF'
[Unit]
Description=Check for available system upgrades
After=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/check-upgrades
EOF

    cat > /etc/systemd/system/check-upgrades.timer << 'EOF'
[Unit]
Description=Daily upgrade check

[Timer]
OnCalendar=daily
Persistent=true
RandomizedDelaySec=1h

[Install]
WantedBy=timers.target
EOF

    # Enable the timer
    systemctl daemon-reload
    systemctl enable check-upgrades.timer
    systemctl start check-upgrades.timer
    
    log_success "Upgrade notification configured"
}

# Configure log rotation for upgrade logs
setup_logrotate() {
    log_step "Configuring log rotation"
    
    cat > /etc/logrotate.d/upgrade-check << 'EOF'
/var/log/upgrade-check.log {
    weekly
    rotate 4
    compress
    missingok
    notifempty
}
EOF

    log_success "Log rotation configured"
}

# Enable and start services
enable_services() {
    log_step "Enabling unattended-upgrades service"
    
    systemctl enable unattended-upgrades
    systemctl start unattended-upgrades
    
    if systemctl is-active --quiet unattended-upgrades; then
        log_success "Unattended-upgrades service is running"
    else
        log_warning "Unattended-upgrades service may not be running"
    fi
}

# Run a dry-run to verify configuration
verify_configuration() {
    log_step "Verifying configuration"
    
    log_info "Running dry-run..."
    if unattended-upgrade --dry-run -v 2>&1 | head -20; then
        log_success "Configuration verified"
    else
        log_warning "Check configuration for potential issues"
    fi
}

# Show status
show_status() {
    log_step "Unattended-upgrades status"
    echo ""
    
    log_info "Systemd timer status:"
    systemctl status apt-daily.timer --no-pager 2>/dev/null || true
    systemctl status apt-daily-upgrade.timer --no-pager 2>/dev/null || true
    
    echo ""
    log_info "Last upgrade log:"
    if [[ -f /var/log/unattended-upgrades/unattended-upgrades.log ]]; then
        tail -10 /var/log/unattended-upgrades/unattended-upgrades.log
    else
        log_info "No upgrade log found yet"
    fi
    
    echo ""
}

# Main function
setup_unattended_upgrades() {
    check_root
    
    log_step "Starting unattended-upgrades configuration"
    print_separator
    
    install_unattended_upgrades
    configure_unattended_upgrades
    configure_auto_upgrades
    configure_needrestart
    setup_upgrade_notification
    setup_logrotate
    enable_services
    verify_configuration
    show_status
    
    print_separator
    log_success "Unattended-upgrades configuration complete"
    log_info "Security updates will be installed automatically"
    log_info "System will reboot at 3 AM if required (when no users logged in)"
    
    save_state "UNATTENDED_UPGRADES_CONFIGURED" "$(date +%Y%m%d_%H%M%S)"
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    setup_unattended_upgrades
fi
